env: "dev"
jwtsecretkey: "asdw1qp3ojsmdalcxz"
server:
  port: ":8080"
database:
  host: "localhost"
  port: "5432"
  db_name: "macan-ai"
  db_password: "qwaq"
  db_username: "qwaq"
  sslmode: "disable"
services:
  resume_parsing_grpc_addr: localhost:50051