env: "dev"
http_server:
  address: "localhost:8081"
  timeout: 4s
  idle_timeout: 60s
database:
  host: "localhost"
  port: "5432"
  db_name: "macan-ai"
  db_password: "postgres"
  db_username: "postgres"
  sslmode: "disable"