// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResumePath struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filepath      string                 `protobuf:"bytes,1,opt,name=filepath,proto3" json:"filepath,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumePath) Reset() {
	*x = ResumePath{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumePath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumePath) ProtoMessage() {}

func (x *ResumePath) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumePath.ProtoReflect.Descriptor instead.
func (*ResumePath) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *ResumePath) GetFilepath() string {
	if x != nil {
		return x.Filepath
	}
	return ""
}

type FullName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FullName) Reset() {
	*x = FullName{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullName) ProtoMessage() {}

func (x *FullName) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullName.ProtoReflect.Descriptor instead.
func (*FullName) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *FullName) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *FullName) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type ContactInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber     string                 `protobuf:"bytes,1,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Email           string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	GithubUrl       string                 `protobuf:"bytes,3,opt,name=githubUrl,proto3" json:"githubUrl,omitempty"`
	LinkedinUrl     string                 `protobuf:"bytes,4,opt,name=linkedinUrl,proto3" json:"linkedinUrl,omitempty"`
	PersonalWebsite string                 `protobuf:"bytes,5,opt,name=personalWebsite,proto3" json:"personalWebsite,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ContactInfo) Reset() {
	*x = ContactInfo{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactInfo) ProtoMessage() {}

func (x *ContactInfo) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactInfo.ProtoReflect.Descriptor instead.
func (*ContactInfo) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *ContactInfo) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *ContactInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ContactInfo) GetGithubUrl() string {
	if x != nil {
		return x.GithubUrl
	}
	return ""
}

func (x *ContactInfo) GetLinkedinUrl() string {
	if x != nil {
		return x.LinkedinUrl
	}
	return ""
}

func (x *ContactInfo) GetPersonalWebsite() string {
	if x != nil {
		return x.PersonalWebsite
	}
	return ""
}

type Period struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         string                 `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           string                 `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Period) Reset() {
	*x = Period{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Period) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Period) ProtoMessage() {}

func (x *Period) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Period.ProtoReflect.Descriptor instead.
func (*Period) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *Period) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *Period) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

type WorkExperience struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CompanyName      string                 `protobuf:"bytes,1,opt,name=companyName,proto3" json:"companyName,omitempty"`
	Position         string                 `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Period           *Period                `protobuf:"bytes,3,opt,name=period,proto3" json:"period,omitempty"`
	Responsibilities []string               `protobuf:"bytes,4,rep,name=responsibilities,proto3" json:"responsibilities,omitempty"`
	Technologies     []string               `protobuf:"bytes,5,rep,name=technologies,proto3" json:"technologies,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WorkExperience) Reset() {
	*x = WorkExperience{}
	mi := &file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkExperience) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkExperience) ProtoMessage() {}

func (x *WorkExperience) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkExperience.ProtoReflect.Descriptor instead.
func (*WorkExperience) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *WorkExperience) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *WorkExperience) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *WorkExperience) GetPeriod() *Period {
	if x != nil {
		return x.Period
	}
	return nil
}

func (x *WorkExperience) GetResponsibilities() []string {
	if x != nil {
		return x.Responsibilities
	}
	return nil
}

func (x *WorkExperience) GetTechnologies() []string {
	if x != nil {
		return x.Technologies
	}
	return nil
}

type Education struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Institution   string                 `protobuf:"bytes,1,opt,name=institution,proto3" json:"institution,omitempty"`
	Major         string                 `protobuf:"bytes,2,opt,name=major,proto3" json:"major,omitempty"`
	DegreeType    string                 `protobuf:"bytes,3,opt,name=degreeType,proto3" json:"degreeType,omitempty"`
	Period        string                 `protobuf:"bytes,4,opt,name=period,proto3" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Education) Reset() {
	*x = Education{}
	mi := &file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Education) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Education) ProtoMessage() {}

func (x *Education) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Education.ProtoReflect.Descriptor instead.
func (*Education) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *Education) GetInstitution() string {
	if x != nil {
		return x.Institution
	}
	return ""
}

func (x *Education) GetMajor() string {
	if x != nil {
		return x.Major
	}
	return ""
}

func (x *Education) GetDegreeType() string {
	if x != nil {
		return x.DegreeType
	}
	return ""
}

func (x *Education) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

type PersonalProjects struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectName   string                 `protobuf:"bytes,1,opt,name=projectName,proto3" json:"projectName,omitempty"`
	Period        string                 `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Technologies  []string               `protobuf:"bytes,4,rep,name=technologies,proto3" json:"technologies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonalProjects) Reset() {
	*x = PersonalProjects{}
	mi := &file_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonalProjects) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalProjects) ProtoMessage() {}

func (x *PersonalProjects) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalProjects.ProtoReflect.Descriptor instead.
func (*PersonalProjects) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

func (x *PersonalProjects) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *PersonalProjects) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *PersonalProjects) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PersonalProjects) GetTechnologies() []string {
	if x != nil {
		return x.Technologies
	}
	return nil
}

type AdditionalInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DesiredSalary   int64                  `protobuf:"varint,1,opt,name=desiredSalary,proto3" json:"desiredSalary,omitempty"`
	RelocationReady bool                   `protobuf:"varint,2,opt,name=relocationReady,proto3" json:"relocationReady,omitempty"`
	RemoteWorkReady bool                   `protobuf:"varint,3,opt,name=remoteWorkReady,proto3" json:"remoteWorkReady,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AdditionalInfo) Reset() {
	*x = AdditionalInfo{}
	mi := &file_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdditionalInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdditionalInfo) ProtoMessage() {}

func (x *AdditionalInfo) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdditionalInfo.ProtoReflect.Descriptor instead.
func (*AdditionalInfo) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{7}
}

func (x *AdditionalInfo) GetDesiredSalary() int64 {
	if x != nil {
		return x.DesiredSalary
	}
	return 0
}

func (x *AdditionalInfo) GetRelocationReady() bool {
	if x != nil {
		return x.RelocationReady
	}
	return false
}

func (x *AdditionalInfo) GetRemoteWorkReady() bool {
	if x != nil {
		return x.RemoteWorkReady
	}
	return false
}

type ResumeData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	FullName       *FullName              `protobuf:"bytes,2,opt,name=fullName,proto3" json:"fullName,omitempty"`
	ContactInfo    *ContactInfo           `protobuf:"bytes,3,opt,name=contactInfo,proto3" json:"contactInfo,omitempty"`
	Summary        string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	Skills         []string               `protobuf:"bytes,5,rep,name=skills,proto3" json:"skills,omitempty"`
	WorkExperience []*WorkExperience      `protobuf:"bytes,6,rep,name=workExperience,proto3" json:"workExperience,omitempty"`
	Education      []*Education           `protobuf:"bytes,7,rep,name=education,proto3" json:"education,omitempty"`
	Projects       []*PersonalProjects    `protobuf:"bytes,8,rep,name=projects,proto3" json:"projects,omitempty"`
	SoftSkills     []string               `protobuf:"bytes,9,rep,name=softSkills,proto3" json:"softSkills,omitempty"`
	AdditionalInfo *AdditionalInfo        `protobuf:"bytes,10,opt,name=additionalInfo,proto3" json:"additionalInfo,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResumeData) Reset() {
	*x = ResumeData{}
	mi := &file_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeData) ProtoMessage() {}

func (x *ResumeData) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeData.ProtoReflect.Descriptor instead.
func (*ResumeData) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{8}
}

func (x *ResumeData) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResumeData) GetFullName() *FullName {
	if x != nil {
		return x.FullName
	}
	return nil
}

func (x *ResumeData) GetContactInfo() *ContactInfo {
	if x != nil {
		return x.ContactInfo
	}
	return nil
}

func (x *ResumeData) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ResumeData) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *ResumeData) GetWorkExperience() []*WorkExperience {
	if x != nil {
		return x.WorkExperience
	}
	return nil
}

func (x *ResumeData) GetEducation() []*Education {
	if x != nil {
		return x.Education
	}
	return nil
}

func (x *ResumeData) GetProjects() []*PersonalProjects {
	if x != nil {
		return x.Projects
	}
	return nil
}

func (x *ResumeData) GetSoftSkills() []string {
	if x != nil {
		return x.SoftSkills
	}
	return nil
}

func (x *ResumeData) GetAdditionalInfo() *AdditionalInfo {
	if x != nil {
		return x.AdditionalInfo
	}
	return nil
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\x0eresume_parsing\"(\n" +
	"\n" +
	"ResumePath\x12\x1a\n" +
	"\bfilepath\x18\x01 \x01(\tR\bfilepath\"D\n" +
	"\bFullName\x12\x1c\n" +
	"\tfirstName\x18\x01 \x01(\tR\tfirstName\x12\x1a\n" +
	"\blastName\x18\x02 \x01(\tR\blastName\"\xaf\x01\n" +
	"\vContactInfo\x12 \n" +
	"\vphoneNumber\x18\x01 \x01(\tR\vphoneNumber\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1c\n" +
	"\tgithubUrl\x18\x03 \x01(\tR\tgithubUrl\x12 \n" +
	"\vlinkedinUrl\x18\x04 \x01(\tR\vlinkedinUrl\x12(\n" +
	"\x0fpersonalWebsite\x18\x05 \x01(\tR\x0fpersonalWebsite\"0\n" +
	"\x06Period\x12\x14\n" +
	"\x05start\x18\x01 \x01(\tR\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\tR\x03end\"\xce\x01\n" +
	"\x0eWorkExperience\x12 \n" +
	"\vcompanyName\x18\x01 \x01(\tR\vcompanyName\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\tR\bposition\x12.\n" +
	"\x06period\x18\x03 \x01(\v2\x16.resume_parsing.PeriodR\x06period\x12*\n" +
	"\x10responsibilities\x18\x04 \x03(\tR\x10responsibilities\x12\"\n" +
	"\ftechnologies\x18\x05 \x03(\tR\ftechnologies\"{\n" +
	"\tEducation\x12 \n" +
	"\vinstitution\x18\x01 \x01(\tR\vinstitution\x12\x14\n" +
	"\x05major\x18\x02 \x01(\tR\x05major\x12\x1e\n" +
	"\n" +
	"degreeType\x18\x03 \x01(\tR\n" +
	"degreeType\x12\x16\n" +
	"\x06period\x18\x04 \x01(\tR\x06period\"\x92\x01\n" +
	"\x10PersonalProjects\x12 \n" +
	"\vprojectName\x18\x01 \x01(\tR\vprojectName\x12\x16\n" +
	"\x06period\x18\x02 \x01(\tR\x06period\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\"\n" +
	"\ftechnologies\x18\x04 \x03(\tR\ftechnologies\"\x8a\x01\n" +
	"\x0eAdditionalInfo\x12$\n" +
	"\rdesiredSalary\x18\x01 \x01(\x03R\rdesiredSalary\x12(\n" +
	"\x0frelocationReady\x18\x02 \x01(\bR\x0frelocationReady\x12(\n" +
	"\x0fremoteWorkReady\x18\x03 \x01(\bR\x0fremoteWorkReady\"\xf4\x03\n" +
	"\n" +
	"ResumeData\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x124\n" +
	"\bfullName\x18\x02 \x01(\v2\x18.resume_parsing.FullNameR\bfullName\x12=\n" +
	"\vcontactInfo\x18\x03 \x01(\v2\x1b.resume_parsing.ContactInfoR\vcontactInfo\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\x16\n" +
	"\x06skills\x18\x05 \x03(\tR\x06skills\x12F\n" +
	"\x0eworkExperience\x18\x06 \x03(\v2\x1e.resume_parsing.WorkExperienceR\x0eworkExperience\x127\n" +
	"\teducation\x18\a \x03(\v2\x19.resume_parsing.EducationR\teducation\x12<\n" +
	"\bprojects\x18\b \x03(\v2 .resume_parsing.PersonalProjectsR\bprojects\x12\x1e\n" +
	"\n" +
	"softSkills\x18\t \x03(\tR\n" +
	"softSkills\x12F\n" +
	"\x0eadditionalInfo\x18\n" +
	" \x01(\v2\x1e.resume_parsing.AdditionalInfoR\x0eadditionalInfo2`\n" +
	"\x14ResumeParsingService\x12H\n" +
	"\x0eSendResumePath\x12\x1a.resume_parsing.ResumePath\x1a\x1a.resume_parsing.ResumeDataB-Z+github.com/qwaq-dev/macan-ai/backend/pkg/pbb\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_service_proto_goTypes = []any{
	(*ResumePath)(nil),       // 0: resume_parsing.ResumePath
	(*FullName)(nil),         // 1: resume_parsing.FullName
	(*ContactInfo)(nil),      // 2: resume_parsing.ContactInfo
	(*Period)(nil),           // 3: resume_parsing.Period
	(*WorkExperience)(nil),   // 4: resume_parsing.WorkExperience
	(*Education)(nil),        // 5: resume_parsing.Education
	(*PersonalProjects)(nil), // 6: resume_parsing.PersonalProjects
	(*AdditionalInfo)(nil),   // 7: resume_parsing.AdditionalInfo
	(*ResumeData)(nil),       // 8: resume_parsing.ResumeData
}
var file_service_proto_depIdxs = []int32{
	3, // 0: resume_parsing.WorkExperience.period:type_name -> resume_parsing.Period
	1, // 1: resume_parsing.ResumeData.fullName:type_name -> resume_parsing.FullName
	2, // 2: resume_parsing.ResumeData.contactInfo:type_name -> resume_parsing.ContactInfo
	4, // 3: resume_parsing.ResumeData.workExperience:type_name -> resume_parsing.WorkExperience
	5, // 4: resume_parsing.ResumeData.education:type_name -> resume_parsing.Education
	6, // 5: resume_parsing.ResumeData.projects:type_name -> resume_parsing.PersonalProjects
	7, // 6: resume_parsing.ResumeData.additionalInfo:type_name -> resume_parsing.AdditionalInfo
	0, // 7: resume_parsing.ResumeParsingService.SendResumePath:input_type -> resume_parsing.ResumePath
	8, // 8: resume_parsing.ResumeParsingService.SendResumePath:output_type -> resume_parsing.ResumeData
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
