// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ResumeParsingService_SendResumePath_FullMethodName = "/resume_parsing.ResumeParsingService/SendResumePath"
)

// ResumeParsingServiceClient is the client API for ResumeParsingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResumeParsingServiceClient interface {
	SendResumePath(ctx context.Context, in *ResumePath, opts ...grpc.CallOption) (*ResumeData, error)
}

type resumeParsingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewResumeParsingServiceClient(cc grpc.ClientConnInterface) ResumeParsingServiceClient {
	return &resumeParsingServiceClient{cc}
}

func (c *resumeParsingServiceClient) SendResumePath(ctx context.Context, in *ResumePath, opts ...grpc.CallOption) (*ResumeData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeData)
	err := c.cc.Invoke(ctx, ResumeParsingService_SendResumePath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResumeParsingServiceServer is the server API for ResumeParsingService service.
// All implementations must embed UnimplementedResumeParsingServiceServer
// for forward compatibility.
type ResumeParsingServiceServer interface {
	SendResumePath(context.Context, *ResumePath) (*ResumeData, error)
	mustEmbedUnimplementedResumeParsingServiceServer()
}

// UnimplementedResumeParsingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedResumeParsingServiceServer struct{}

func (UnimplementedResumeParsingServiceServer) SendResumePath(context.Context, *ResumePath) (*ResumeData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendResumePath not implemented")
}
func (UnimplementedResumeParsingServiceServer) mustEmbedUnimplementedResumeParsingServiceServer() {}
func (UnimplementedResumeParsingServiceServer) testEmbeddedByValue()                              {}

// UnsafeResumeParsingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResumeParsingServiceServer will
// result in compilation errors.
type UnsafeResumeParsingServiceServer interface {
	mustEmbedUnimplementedResumeParsingServiceServer()
}

func RegisterResumeParsingServiceServer(s grpc.ServiceRegistrar, srv ResumeParsingServiceServer) {
	// If the following call pancis, it indicates UnimplementedResumeParsingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ResumeParsingService_ServiceDesc, srv)
}

func _ResumeParsingService_SendResumePath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumePath)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResumeParsingServiceServer).SendResumePath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResumeParsingService_SendResumePath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResumeParsingServiceServer).SendResumePath(ctx, req.(*ResumePath))
	}
	return interceptor(ctx, in, info, handler)
}

// ResumeParsingService_ServiceDesc is the grpc.ServiceDesc for ResumeParsingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResumeParsingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "resume_parsing.ResumeParsingService",
	HandlerType: (*ResumeParsingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendResumePath",
			Handler:    _ResumeParsingService_SendResumePath_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
